baseURL = "https://notes.hanspistor.dev/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "hugo-book"

[taxonomies]
tags = "tags"

[params]
BookToC = false
BookTheme = "auto"
BookSection = "*"

[markup.goldmark.renderer]
unsafe = true